apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: strontium-storage-class
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /media/onlinejudge95/data-disk-1/k8s-pv
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sandisk-storage-class
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /media/onlinejudge95/data-disk-2/k8s-pv
volumeBindingMode: WaitForFirstConsumer
