apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg
spec:
  description: "Cloud native postgres cluster"
  instances: 1
  storage:
    storageClass: strontium-storage-class
    size: 4Gi
